//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDnevnikM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Godine> Godines { get; set; }
        public virtual DbSet<Ocene> Ocenes { get; set; }
        public virtual DbSet<Ocenjivanje> Ocenjivanjes { get; set; }
        public virtual DbSet<Odeljenja> Odeljenjas { get; set; }
        public virtual DbSet<Predmeti> Predmetis { get; set; }
        public virtual DbSet<Prof_Predm> Prof_Predm { get; set; }
        public virtual DbSet<Profesori> Profesoris { get; set; }
        public virtual DbSet<Staresine> Staresines { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Ucenici> Ucenicis { get; set; }
    
        public virtual ObjectResult<Godine> SP_God_Odelj(string opis)
        {
            var opisParameter = opis != null ?
                new ObjectParameter("Opis", opis) :
                new ObjectParameter("Opis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Godine>("SP_God_Odelj", opisParameter);
        }
    
        public virtual ObjectResult<Godine> SP_God_Odelj(string opis, MergeOption mergeOption)
        {
            var opisParameter = opis != null ?
                new ObjectParameter("Opis", opis) :
                new ObjectParameter("Opis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Godine>("SP_God_Odelj", mergeOption, opisParameter);
        }
    
       
    
        public virtual ObjectResult<Odeljenja> Odelj_ListaUcen1(string matBrOdeljenja)
        {
            var matBrOdeljenjaParameter = matBrOdeljenja != null ?
                new ObjectParameter("MatBrOdeljenja", matBrOdeljenja) :
                new ObjectParameter("MatBrOdeljenja", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Odeljenja>("Odelj_ListaUcen1", matBrOdeljenjaParameter);
        }
    
        public virtual ObjectResult<Odeljenja> Odelj_ListaUcen1(string matBrOdeljenja, MergeOption mergeOption)
        {
            var matBrOdeljenjaParameter = matBrOdeljenja != null ?
                new ObjectParameter("MatBrOdeljenja", matBrOdeljenja) :
                new ObjectParameter("MatBrOdeljenja", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Odeljenja>("Odelj_ListaUcen1", mergeOption, matBrOdeljenjaParameter);
        }
    }
}
