//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDnevnikM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocenjivanje
    {
        public int OcenjivanjeID { get; set; }
        public int PredmetID { get; set; }
        public int UcenikID { get; set; }
        public int OcenaID { get; set; }
        public string FormattedDate => DatumOcenj.ToShortDateString();
        public System.DateTime DatumOcenj { get; set; }
        public string Komentar { get; set; }
    
        public virtual Ocene Ocene { get; set; }
        public virtual Predmeti Predmeti { get; set; }
        public virtual Ucenici Ucenici { get; set; }
    }
}
