//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDnevnikM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ocenjivanje
    {
        public int OcenjivanjeID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Unesite ime")]
        public int PredmetID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Unesite ime")]
        public int UcenikID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Unesite ime")]
        public int OcenaID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Unesite datum ocenjivanja")]

        public string FormattedDate => DatumOcenj.ToShortDateString();

        public System.DateTime DatumOcenj { get; set; }

        public string Komentar { get; set; }
    
        public virtual Ocene Ocene { get; set; }
        public virtual Predmeti Predmeti { get; set; }
        public virtual Ucenici Ucenici { get; set; }
    }
}
