//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDnevnikM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocene
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ocene()
        {
            this.Ocenjivanjes = new HashSet<Ocenjivanje>();
        }
    
        public int OcenaID { get; set; }
        public Nullable<int> Ocena { get; set; }
        public string OpisOcene { get; set; }
        public string TipOcene { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocenjivanje> Ocenjivanjes { get; set; }
    }
}
