//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDnevnikM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odeljenja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odeljenja()
        {
            this.Staresines = new HashSet<Staresine>();
            this.Ucenicis = new HashSet<Ucenici>();
        }
    
        public int OdeljenjeID { get; set; }
        public int GodinaID { get; set; }
        public int BrojOdeljenja { get; set; }
        public int GodinaUpisa { get; set; }
        public string MatBrOdeljenja { get; set; }
        public Nullable<int> ProfesorID { get; set; }
    
        public virtual Godine Godine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staresine> Staresines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ucenici> Ucenicis { get; set; }
    }
}
