//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDnevnikM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staresine
    {
        public int StaresinaID { get; set; }
        public int ProfesorID { get; set; }
        public int OdeljenjeID { get; set; }
    
        public virtual Odeljenja Odeljenja { get; set; }
        public virtual Profesori Profesori { get; set; }
    }
}
