//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDnevnikM.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Ucenici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ucenici()
        {
            this.Ocenjivanjes = new HashSet<Ocenjivanje>();
        }
    
        public int UcenikID { get; set; }
		[Required(AllowEmptyStrings = false, ErrorMessage = "Unesite odeljenje")]
		public int OdeljenjeID { get; set; }
		[Required(AllowEmptyStrings = false, ErrorMessage = "Unesite ime")]
		public string Ime { get; set; }
		[Required(AllowEmptyStrings = false, ErrorMessage = "Unesite prezime ")]
		public string Prezime { get; set; }
		[Required(AllowEmptyStrings = false, ErrorMessage = "Unesite datum rodjenja")]
		public string FormattedDate => DatumRodjenja.ToShortDateString();
		public System.DateTime DatumRodjenja { get; set; }
		[Required(AllowEmptyStrings = false, ErrorMessage = "Unesite adresu")]
		public string Adresa { get; set; }
		[Required(AllowEmptyStrings = false, ErrorMessage = "Unesite godinu upisa")]
		public short GodinaUpisa { get; set; }
		[Required(AllowEmptyStrings = false, ErrorMessage = "Unesite redni broj u odeljenju")]
		public int RedBrUOdeljenju { get; set; }
        public string Lozinka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocenjivanje> Ocenjivanjes { get; set; }
        public virtual Odeljenja Odeljenja { get; set; }
    }
}
